<a href="https://colab.research.google.com/github/ABHIRAJAWAT-07/AbhiRajawat-07/blob/main/Column_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)
X_train

    age  gender  fever   cough       city
72   83  Female  101.0    Mild    Kolkata
25   23    Male    NaN    Mild     Mumbai
40   49  Female  102.0    Mild      Delhi
16   69  Female  103.0    Mild    Kolkata
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
49   44    Male  104.0    Mild     Mumbai
78   11    Male  100.0    Mild  Bangalore
99   10  Female   98.0  Strong    Kolkata
42   27    Male  100.0    Mild      Delhi
39   50  Female  103.0    Mild    Kolkata

[80 rows x 5 columns]

In [7]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [8]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

(80, 1)

In [24]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False)

In [25]:
X_train_gender_city = ohe.fit_transform(
    X_train[['gender', 'city']]
)

In [26]:
X_test_gender_city = ohe.transform(
    X_test[['gender', 'city']]
)

In [27]:
import numpy as np

X_train_transformed = np.concatenate(
    (X_train_age,
     X_train_fever,
     X_train_gender_city,
     X_train_cough),
    axis=1
)

In [28]:
X_test_transformed = np.concatenate(
    (X_test_age,
     X_test_fever,
     X_test_gender_city,
     X_test_cough),
    axis=1
)

In [34]:
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [32]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [33]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [12]:
from sklearn.compose import ColumnTransformer

In [13]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [14]:
transformer.fit_transform(X_train).shape

NameError: name 'transformer' is not defined

In [15]:
transformer.transform(X_test).shape

NameError: name 'transformer' is not defined

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer

preprocessor = ColumnTransformer(transformers=[

    ('imputer', SimpleImputer(strategy='most_frequent'), ['fever']),

    ('ordinal', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),

    ('onehot', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])

], remainder='passthrough')

In [17]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [20]:
preprocessor.fit_transform(X_train).shape

(80, 7)

In [21]:
preprocessor.transform(X_test).shape

(20, 7)